# Generated by Django 5.2.8 on 2025-11-22 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('id_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='תעודת זהות חייבת להכיל 9 ספרות', regex='^\\d{9}$')], verbose_name='תעודת זהות')),
                ('class_name', models.CharField(max_length=50, verbose_name='כיתה')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='מספר טלפון לא תקין', regex='^0\\d{9}$')], verbose_name='טלפון')),
                ('address', models.TextField(blank=True, null=True, verbose_name='כתובת')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='תאריך לידה')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'תלמיד',
                'verbose_name_plural': 'תלמידים',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
