# Generated by Django 5.2.8 on 2026-01-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50, verbose_name='ישות')),
                ('entity_id', models.IntegerField(verbose_name='מזהה ישות')),
                ('field', models.CharField(max_length=50, verbose_name='שדה')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='ערך ישן')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='ערך חדש')),
                ('user', models.CharField(max_length=50, verbose_name='משתמש')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='תאריך ושעה')),
            ],
            options={
                'verbose_name': 'לוג שינוי',
                'verbose_name_plural': 'לוג שינויים',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='שם שכבה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'שכבה',
                'verbose_name_plural': 'שכבות',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/', verbose_name='תמונת פרופיל'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='שם משפחה'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.IntegerField(choices=[(1, 'הערכה 1'), (2, 'הערכה 2'), (3, 'הערכה 3'), (4, 'הערכה 4'), (5, 'הערכה 5')], verbose_name='סוג הערכה')),
                ('value', models.FloatField(verbose_name='ציון')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student', verbose_name='תלמיד')),
            ],
            options={
                'verbose_name': 'הערכה',
                'verbose_name_plural': 'הערכות',
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='שכבה'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='שם הקבצה')),
                ('teacher', models.CharField(max_length=50, verbose_name='שם מורה')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade', verbose_name='שכבה')),
            ],
            options={
                'verbose_name': 'הקבצה',
                'verbose_name_plural': 'הקבצות',
                'ordering': ['grade', 'name'],
                'unique_together': {('name', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='הקבצה'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('status', models.CharField(choices=[('present', 'נוכח'), ('absent', 'נעדר'), ('late', 'מאחר')], max_length=10, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='תלמיד')),
            ],
            options={
                'verbose_name': 'נוכחות',
                'verbose_name_plural': 'נוכחויות',
                'ordering': ['-date', 'student'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
